- library/s3.py
- tests/test_s3.py
#4 
run test via the following:
```bash
poetry run pytest tests/test_s3.py -s
```
> s3 utilities

- library/ingest.py
- tests/test_ingest.py
simplifying ingestors using decorators, also standardize processes across different destinations
> Ingestor decorator

- .pre-commit-config.yaml
- README.md
- poetry.lock
- pyproject.toml
Requires `pre-commit install` to set up the git hook scripts
> Set up pre-commit

- library/cli.py
#27 
+ Deletes a file from s3 using either a full key, or specific arguments
+ If only name is provided, all files of that dataset get dropped
+ If name and version are provided, all files of that dataset and version get dropped
+ If name, version, and extension are provided, a specific file gets dropped
I am open to other approaches if this is too dangerous.
> Add delete CLI command

- tests/test_archive.py
> Add test of archive using name rather than path

- library/archive.py
- library/cli.py
- self.s3
- one time declaration of s3
> small fixes

- library/s3.py
- tests/test_s3.py
> Set metadata keys to lower in s3.info and modify test

- library/ingest.py
- pyproject.toml
> Implement makeValid

- library/templates/dcp_commercialoverlay.yml
- library/templates/dcp_limitedheight.yml
- library/templates/dcp_mih.yml
- library/templates/dcp_specialpurpose.yml
- library/templates/dcp_specialpurposesubdistricts.yml
- library/templates/dcp_zoningdistricts.yml
- library/templates/dcp_zoningmapamendments.yml
- library/templates/dcp_zoningmapindex.yml
- library/templates/dcp_zoningtaxlots.yml
`poetry run library archive -n dcp_zoningtaxlots -v 20201231`
zoning taxlots requires explicit version declaration
> adding zoning taxlots related data recipes

- library/archive.py
- library/cli.py
- poetry.lock
- pyproject.toml
`poetry run library show nypl_libraries `
`poetry run library show nypl_libraries --json` will show json info -> which can be parsed using jq
`poetry run library show dof_dtm --json | jq -r '.latest'` extract latest version using jq
- adding sort by day time
- not all files needs to be shown
> Adding a simplified show command that show relevant info

- .github/workflows/docs.yml
- README.md
- library/__init__.py
- tests/__init__.py
- tests/test_archive.py
- tests/test_ingest.py
- tests/test_s3.py
because it's only used in tests
> remove recipe_engine from the library pacakge

- library/templates/dcp_commercialoverlay.yml
- library/templates/dcp_limitedheight.yml
- library/templates/dcp_mih.yml
- library/templates/dcp_specialpurpose.yml
- library/templates/dcp_specialpurposesubdistricts.yml
- library/templates/dcp_zoningdistricts.yml
- library/templates/dcp_zoningmapamendments.yml
- library/templates/dof_dtm.yml
> transition to edm-publishing

- library/templates/dpr_greenthumb.yml
> adding greenthumb

- library/script/doe_lcgms.py
- library/script/doe_pepmeetingurls.py
- library/templates/doe_lcgms.yml
- library/templates/doe_pepmeetingurls.yml
- poetry.lock
- pyproject.toml
> adding doe scrapped datasets

- library/templates/dcp_colp.yml
> set dependents values for dcp_colp

- library/templates/nycha_communitycenters.yml
> Set source SRS to EPSG:4326

- library/templates/nycha_policeservice.yml
#69 #70 filename: nycha_policeservice.yml
> Set source SRS and added socrata parameter

- library/templates/dcp_atomicpolygons.yml
Subissue #78 
Issue #58 
I tested it and it's working.
> dcp_atomicpolygons tested

- library/templates/doitt_buildingfootprints_historical.yml
#75 filename: doitt_buildingfootprints_historical.yml
> Set uid for doitt_buildingfootprints_historical.yml to qgyt-j5ak

- library/templates/doitt_buildingfootprints.yml
#74 filename: doitt_buildingfootprints.yml
> Set uid for doitt_buildingfootprints to uic8-njst

- library/templates/dcp_boroboundaries.yml
- library/templates/dcp_boroboundaries_wi.yml
- library/templates/doitt_buildingfootprints.yml
> dcp_boroboundaries and dcp_boroboundaries_wi created and tested

- library/templates/dcp_cdboundaries.yml
- library/templates/dcp_cdboundaries_wi.yml
> dcp_cdboundaries dcp_cdboundaries_wi created and tested

- library/templates/dcp_censustracts.yml
- library/templates/dcp_censustracts_wi.yml
subissue #86 
issue #58
files created and tested
> dcp_censustracts and dcp_censustracts_wi created

- library/templates/dcp_stateassemblydistricts.yml
- library/templates/dcp_stateassemblydistricts_wi.yml
> dcp_stateassemblydistricts and dcp_stateassemblydistricts_wi created

- library/templates/dcp_censusblocks.yml
- library/templates/dcp_censusblocks_wi.yml
subissue #84 
issue #58
files created and tested.
> dcp_censusblocks and dcp_censusblocks_wi created

- library/templates/dcp_municipalcourtdistricts.yml
- library/templates/dcp_municipalcourtdistricts_wi.yml
Files created and tested
Subissue #96 
Issue #58
> dcp_municipalcourtdistricts and dcp_municipalcourtdistricts_wi created

- library/templates/dcp_councildistricts.yml
- library/templates/dcp_councildistricts_wi.yml
Subissue #100 
Issue #58 
Files created and tested
> dcp_councildistricts and dcp_councildistricts_wi

- library/templates/dcp_firecompanies.yml
- library/templates/dcp_healtharea.yml
- library/templates/dcp_healthcenter.yml
- library/templates/dcp_policeprecincts.yml
- library/templates/dcp_schooldistricts.yml
Subissue #104 
Issue #58 
Files created and tested
> Config files for school, police, health, and fire boundaries created

- library/templates/dcp_addresspoints.yml
> File created and tested

- library/validator.py
- tests/test_validator.py
> WIP Validator class

- library/validator.py
- poetry.lock
- pyproject.toml
- tests/data/test_none.yml
- tests/test_validator.py
Part of issue #106 
So far it validates the following:
- Tree structure based on our current files.
- Only one source from either url, socrata or script
- Dataset name matching with destination name
TODO:
- Define __call__ method
- Rewrite constructor
- Set cached properties
> WIP - Validator Class

- library/templates/dcp_addresspoints.yml
- library/templates/dcp_boroboundaries.yml
- library/templates/dcp_boroboundaries_wi.yml
Resubmitting clean pull request
> Address points and boro boundaries.

- library/validator.py
Only dataset_name_matches need to be redone as a property.
> Added @property decorator to check functions

- library/validator.py
- tests/test_validator.py
elated to #123. Modified test file to reflect the new way to call the function
> Added @property decorator to dataset_name_matches

- library/validator.py
- tests/test_validator.py
Related to #124. Validator class is now callable. I also added additional geometry values to be accepted.
> Defined and tested __call__ method

- library/validator.py
- tests/test_validator.py
Reverts NYCPlanning/db-data-library#127
> Revert "Defined and tested __call__ method"

- library/templates/dcp_school_districts.yml
> Rename dcp_schooldistricts to dcp_school_districts

- library/templates/dcp_commercialoverlay.yml
- library/templates/dcp_edesignation.yml
- library/templates/dcp_limitedheight.yml
- library/templates/dcp_specialpurpose.yml
- library/templates/dcp_specialpurposesubdistricts.yml
- library/templates/dcp_zoningdistricts.yml
- library/templates/dcp_zoningmapamendments.yml
- library/templates/dof_condo.yml
- library/templates/dof_dtm.yml
- library/templates/dof_shoreline.yml
And add missing dcp_edesignation template.
> Fix GIS paths for PLUTO inputs

- library/templates/doitt_zipcodeboundaries.yml
- library/templates/fema_firms2007_100yr.yml
- library/templates/fema_pfirms2015_100yr.yml
- https://data-library-app.herokuapp.com/?dataset=fema_pfirms2015_100yr
- https://data-library-app.herokuapp.com/?dataset=fema_firms2007_100yr
- https://data-library-app.herokuapp.com/?dataset=doitt_zipcodeboundaries
these 3 datasets never change, and will never need to be updated
> adding remaining 3 pluto templates

- library/utils.py
Also the test didn't reveal this issue because we check if file exists first
> previous local file handler didnt consider zipped local file

- library/templates/dca_operatingbusinesses.yml
- library/templates/dfta_contracts.yml
- library/templates/doe_busroutesgarages.yml
adding  - "GEOMETRY=AS_WKT" so that we have formated and reprojected spatial information in the csv under the field name WKT
> facdb source templates fixes

- library/templates/bpl_libraries.yml
- library/templates/dca_opratingbusinesses.yml
- library/templates/dcla_culturalinstitutions.yml
- library/templates/dfta_contracts.yml
- library/templates/doe_busroutesgarages.yml
- library/templates/dohmh_daycare.yml
- library/templates/dpr_capitalprojects.yml
- library/templates/dpr_parksproperties.yml
- library/templates/dycd_afterschoolprograms.yml
- library/templates/fdny_firehouses.yml
- library/templates/hhc_hospitals.yml
- library/templates/nycha_communitycenters.yml
- library/templates/nycha_policeservice.yml
- library/templates/nypl_libraries.yml
- library/templates/qpl_libraries.yml
- library/templates/sbs_workforce1.yml
- library/templates/uscourts_courts.yml
> FacDB Socrata Inputs

- library/templates/dcp_pops.yml
Manually downloaded data from POPs app and uploaded to the tmp folder in s3. Renamed file to remove download date.
> Add dcp_pops

- tests/test_archive.py
> Add test 6 to check for inplace compression of shp

- library/config.py
- library/script/nysed_nonpublicenrollment.py
- library/templates/nysed_nonpublicenrollment.yml
- poetry.lock
- pyproject.toml
nysed_nonpublicenrollment is part of dysd active institutions
> adding nysed_nonpublicenrollment

- library/templates/usdot_airports.yml
- library/templates/usdot_ports.yml
> Add as_wkt to usdot datasets

- library/templates/sca_enrollment_capacity.yml
Used in FacDB doe_lcgms pipeline
> Add sca_enrollment_capacity

- library/templates/dcas_ipis.yml
- library/templates/dof_air_rights_lots.yml
> Add COLP inputs

- library/templates/dot_projects_intersections.yml
- library/templates/dot_projects_streets.yml
> Add dot_projects_intersections.yml and dot_projects_streets.yml

- library/templates/ddc_capitalprojects_infrastructure.yml
- library/templates/ddc_capitalprojects_publicbuildings.yml
https://github.com/NYCPlanning/db-cpdb/issues/74
> Split DDC and fix building geom type

- library/templates/dcp_mappluto.yml
Adding as_wkt for mappluto yml template file
> Update mappluto.yml with as_wkt

- library/templates/dcp_stateassemblydistricts.yml
- library/templates/dcp_stateassemblydistricts_wi.yml
Both with and without water. got description from metadata pdf
> added templates for state assembly districts

- library/templates/dcp_congressionaldistricts.yml
Same approach used to download state senate districts
> Download congressional districts directly from web

- library/templates/doi_evictions.yml
- library/templates/lpc_historic_district_areas.yml
New dataset which is based off existing landmark preservation commission historic districts. It's already been run and populated a new folder in edm-recipes space
> Add landmark preservation comission historic district district areas

- .github/workflows/quaterly-updates.yml
Ran the workflow after making the spelling fix and it added police precincts version 21d
> Fix spelling of police precincts dataset

- library/templates/doitt_buildingfootprints_historical.yml
need to match uid to open data url
> update socrata uid for the doitt_buildingfootprints_historical.yml 

- library/templates/dcp_cb2010.yml
- library/templates/dcp_cb2010_wi.yml
- library/templates/dcp_cb2020.yml
- library/templates/dcp_cb2020_wi.yml
#217
Updates source data projection for census block datasets to LI State Plane.  Issue is related to issue 315 in pluto
> updating source data projection

- library/templates/dcp_mappluto_clipped.yml
- library/templates/dcp_mappluto_historical.yml
- library/templates/dcp_mappluto_wi.yml
- library/templates/dcp_pluto.yml
- library/templates/pluto_corrections.yml
These templates will be pushed to [our data library image](https://hub.docker.com/r/nycplanning/library/tags) so that the [pluto publishing action can reference them by name](https://github.com/NYCPlanning/db-pluto/blob/main/.github/workflows/publish.yml). This [page on the docker website](https://docs.docker.com/docker-hub/repos/#:~:text=To%20push%20an%20image%20to,docs%2Fbase%3Atesting%20) has direction how to push these changes
> Copy templates from pluto

- .github/workflows/update_image.yml
Tiny PR 🔻 
Left in an unnecessary and misspelled string
> remove extra string

- library/templates/doe_universalprek.yml
The version of universal pre-k we use for the 2022 Q2 build of facDB we got via email. Previously we pulled it directly from the internet
> Get universal prek via email

- .github/workflows/single-runner.yml
- library/templates/dcp_pluto.yml
Addresses issue 270 but limited to just `dcp_pluto`, One reviewer required 👍 
This PR addresses the url path change due to the server for Bytes of the Big Apple.
> update path url for dcp_pluto to bytes

- library/templates/dcp_cb2010.yml
- library/templates/dcp_cb2010_wi.yml
One reviewer required. Addresses issue #278 and two tasks in #272. 
> Update URL path to `dcp_cb2010_wi` & `dcp_cb2010`

- library/templates/dcp_cdboundaries.yml
- library/templates/dcp_cdboundaries_wi.yml
One reviewer required. Addresses issue #282  and two tasks in #272 .
> update path url `dcp_cdboundaries_wi` and `dcp_cdboundaries`

- library/templates/dcp_statesenatedistricts.yml
- library/templates/dcp_statesenatedistricts_wi.yml
#295 see #272 for spike issue
Two in one for state senate district and water included
no downstream impacts.
> update url path for `dcp_statesenatedistricts` and `dcp_statesenatedistricts_wi`

- library/templates/dcp_policeprecincts.yml
- library/templates/dcp_school_districts.yml
#297 see #272 for spike ticket
update the school districts and police princts
> update url for `dcp_policeprecincts` and `dcp_school_districts`

- library/templates/dcp_firecompanies.yml
- library/templates/dcp_healthareas.yml
- library/templates/dcp_healthcenters.yml
#309 spike ticket #272
update the last three `dcp_healthcenters`, `dcp_healthareas` & `dcp_firecompanies`
> update url `dcp_healthcenters`, `dcp_healthareas` & `dcp_firecompanies`

- library/templates/dcp_electiondistricts.yml
- library/templates/dcp_electiondistricts_wi.yml
One reviewer required. Addresses issue #314 and two tasks in #272 
> Update `dcp_electiondistricts_wi` and `dcp_electiondistricts`

- library/templates/dcp_councildistricts.yml
- library/templates/dcp_councildistricts_wi.yml
One reviewer required. Addresses issue #301 and two tasks in #272.
> Update path for `dcp_councildistricts_wi'  and `dcp_councildistricts`

- library/templates/dcp_municipalcourtdistricts.yml
- library/templates/dcp_municipalcourtdistricts_wi.yml
#304 see spike ticket #272
update `dcp_municipalcourtdistricts` and `dcp_municipalcourtdistricts_wi` urls
> update url for `dcp_municipalcourtdistricts` and `dcp_municipalcourtdistricts_wi`

- library/templates/dcp_colp.yml
One reviewer required. Addresses issue #286 and one task in #272 
> update `dcp_colp` url path

- library/templates/nysoasas_programs.yml
Addresses issue #334. One reviewer required.
Name of the csv file changed between the last data ingestion.
> Change URL path file name 

- library/templates/dcp_pops.yml
One reviewer required. Addresses issue #348
> Change path `dcp_pops`

- README.md
* sandbox branch and pr to get more familiar with this repo
* potentially fix failing tests
> WIP - sandbox

- library/templates/dcas_ipis.yml
Simple PR updating description to hopefully avoid future issues with Queens dates/hyphenated addresses. Addresses issue #359.
> updated dcas description with warning

- library/templates/dcp_pad.yml
> typo in path for dcp_pad template

- library/config.py
This was a tough one. Somehow specified creation of details within an if statement
> Fix execution details

- .github/workflows/quaterly-updates.yml
- library/script/dcp_facilities_with_unmapped.py
- library/templates/dcp_facilities.yml
- library/templates/dcp_facilities_with_unmapped.yml
- library/templates/dpr_park_access_zone.yml
Initial purpose was to update dpr_park_access uid - Open data updates failing, seems like uid changed
https://github.com/NYCPlanning/db-data-library/actions/runs/4969528641
> 2023 Q2 CPDB build maintenance

- library/ingest.py
- library/script/dcp_facilities_with_unmapped.py
- library/script/nysed_nonpublicenrollment.py
- library/templates/nysdec_lands.yml
- library/templates/nysed_nonpublicenrollment.yml
This is just a handful of various tweaks/notes made during the facdb data ingestion. (Note that one of the commits is just black'ing the ingestion.py file, so going commit-by-commit is a touch easier)
> Ar fac updates

- library/s3.py
Callback should take advance kwarg rather than completed
> Fix rich progress bar
