NYCPlanning/db-data-library

- library/s3.py
- tests/test_s3.py
- adding put/rm to make sure each test cases are independent of each other
- allow different forms of input for rm so it's more flexible to use e.g.
```python
s3.rm('file')
s3.rm('file1', 'file2')
s3.rm(*['file1', 'file2'])
```
to test all:
`poetry run pytest tests/test_s3.py -s`
to test a specific function:
`poetry run pytest tests/test_s3.py::test_s3_ls -s`
> note the `-s` flag is optional, it allows print output (via stdout) to be included in the test output, otherwise they get ignored
it seems like digitalocean has rate limits on API calls, sometimes `cp` and `mv` would fail, sometimes not. this is a [known issue](https://www.digitalocean.com/community/questions/rate-limiting-on-spaces). but the code works fine with minio, if we swap out the credentials
> S3 implementation patch

- library/archive.py
- library/cli.py
- library/s3.py
- library/templates/nypl_libraries.yml
- tests/test_s3.py
#26 
+ Modifies`put`, `cp`, and `mv` functions in s3 to pass a dict as custom s3 metadata
+ Modifies archive `__call__` function to keep version s3 metadata when writing a file to latest -- we can replace/expand this with other metadata as desired
+ Adds `show` as a CLI command with options
+ Show all files available in library for a given dataset name
+ Show all files available in library for a given dataset name, along with last upload date
+ Show all files available in library for a given dataset name, along with version. For all files except for those in latest, version and directory should be the same.
> Add show command

- library/archive.py
#29 
After uploading file to latest, finds other files in latest where the version is not the same as the one uploaded then removes them.
> Add step to remove old versions from latest

- library/validator.py
- tests/test_validator.py
Part of issue #106 
File is loaded in constructor and checks can be called as properties without parameters (Except for dataset_name_matches(name)). Renamed validate_file check to file_is_valid for readability when it's called.
To do next: assert correct file extension (.yml or .yaml) in constructor. This way the validator cannot be instantiated without a proper file path. Also, get file name as a property so it can be removed from dataset_name_matches
PD: I initially committed and pull request was not showing up. I reverted and push again until PR showed again. Apologize for the many  commits
> File is a cached property. Checks do not require file as parameter

- library/validator.py
Related to #120. I created a private method __check_extension to validate if file path points to a .yml or .yaml file. Maybe I should rename the function in a more descriptive way (i.e __valid_extension). Now if you try to instantiate a Validator object with an invalid path you will get an exception.
> Rewrote __init__ to validate path before initializing

- library/config.py
- library/validator.py
- tests/data/socrata.yml
- tests/data/url.yml
- tests/test_validator.py
Part of #129. I made a partial version of validator to return true on all checks. Called validator in `config.compute()`. If `validator()` returns true, compute proceeds to parse the unrendered file. Otherwise, compute returns `None`.
The new version of validator will take an already parsed yml file
> Integrating validator methods into config

- library/templates/dsny_frequencies.yml
- library/templates/lpc_historic_districts.yml
- library/templates/lpc_landmarks.yml
these tables have geometry columns instead of lat lon, so we need to use geom_possible_name
also we need to make sure that they have sql pgdump file included in the latest folder, otherwise, pluto cannot pick it up (e.g. parks property and dpr_greenthumb)
> Update Pluto source table config

- library/templates/nysdec_lands.yml
- library/templates/nysdec_solidwaste.yml
- library/templates/nysdoh_healthfacilities.yml
- library/templates/nysdoh_nursinghomes.yml
- library/templates/nysoasas_programs.yml
- library/templates/nysopwdd_providers.yml
- library/templates/nysparks_historicplaces.yml
- library/templates/nysparks_parks.yml
- library/templates/usdot_airports.yml
- library/templates/usdot_ports.yml
#138 
Currently, nysoasas_programs requires specifying current date in the form dd-Mon-yy:
Example usage:
`poetry run library archive -s -c -l -v 01-Apr-21 -n nysoasas_programs`
There might be a way of formatting current date to be able to use the default version as an enhancement.
> FacDB URL sources

- .gitignore
- library.sh
the bash wrapper works for all python cli commands, 
all we have to do is to run 
`./library init` to initialize docker container 
then we can replace all `library` with `./library.sh` to run commands normally
This PR is aimed to retire DO code-server in favor of local devcontainer and google cloud shell dev environment
> adding a bash wrapper for db-data-library

- library/templates/dot_projects_bridges.yml
- library/templates/edc_capitalprojects.yml
#190 We receive four spatial datasets from DOT, DDC, EDC via email. Refactor yml files so that they remain consistent and are downloaded using the similar tmp method
> Change yml files to match convention

- library/templates/fisa_capitalcommitments.yml
When updating the data library files for cpdb, the DE team thought it made more sense to keep the csv files we get via email or update locally should be stored in the temporary folder so changed the file path in the `fisa_capitalcommitment` template
> add updated path to tmp/library instead of the root of the repo 

- library/templates/nysdec_lands.yml
Refer #221 for the descriotion of the issue
change the workflow for nysdec_lands to point the new location of the shapefile. The existing process handles the change nicely even though the file format changes from a geojson to a zip shapefile on the remote address.
It is worth noting that the new version of this file does not include some of those records in the previous versions such as the campgrounds which cause the archived csv to be smaller in size compared to the previous versions. It was tested in the loading process with facdb that this won't be an issue where campgrounds are not included in the final facdb anyway. The last version compared to the 20220421 version increases the number of records from 26 to 27 in facdb for this source data.
> change nysdec_lands url to the new shapefile

- library/templates/foodbankny_foodbanks.yml
- library/templates/nysdec_lands.yml
- library/templates/nysed_activeinstitutions.yml
I uploaded three datasets for the [dataloading step of the 2022 Q1 build of facDB](https://github.com/NYCPlanning/db-facilities/issues/526) that required tweaking the upload process in data library. 
- `nysdec_lands` data is now posted online as a shapefile instead of a geojson and the path in the corresponding template reflects this
- `foodbanknyc_foodbanks` now reads a .csv instead of a .kml as per the instructions in the wiki
- `nysed_activeinstitutions` now points to a file with the same name it's downloaded as
None of these changes are vital, but in a situation where the data doesn't change for the next build then we can use these templates again
> Change path for some manual upload datasets

- library/templates/dcp_dot_trafficinjuries.yml
New dataset name is dcp_dot_trafficinjuries. Think this is better than crashes as pedestrians getting hit by cars isn't really a "crash" to me. Plus not all crashes result in injuries. 
Files are in https://cloud.digitalocean.com/spaces/edm-recipes?i=266877&path=datasets%2Fdcp_dot_trafficinjuries%2F
> Traffic Injuries and Fatalities

- library/templates/dot_bridgehouses.yml
- library/templates/dot_ferryterminals.yml
- library/templates/dot_mannedfacilities.yml
- library/templates/dot_pedplazas.yml
- library/templates/dot_publicparking.yml
This PR addresses Department of Transporatation (DOT) datasets we get via email (there are currently 5 - `dot_bridgehouese, dot_ferryterminals, dot_mannedfacilities, dot_pedplazas, dot_publicparking`) as written in issue #234. I wanted to add updated description information to highlight how to download the data via data-library if we receive the data as part of geodatabase instead of a stand alone shapefile. Simple changes to the description for all 5 templates
> update dot templates that require manual upload with better directions

- library/templates/edc_capitalprojects.yml
After building cpdb, we realized that the latest edc_capitalprojects data that we receive from edc via email has a different geometry than what was previously given to us. This PR addresses updating the source geometry (srs/epsg) so that a correct conversion can happen and adds a description to guide engineers on how to troubleshoot this issue.
> update source geometry for `edc_capitalprojects` 

- library/script/dcp_facilities_with_unmapped.py
- library/templates/dcp_facilities_with_unmapped.yml
`dcp_facilities_with_unmapped` pulls from the .csv on bytes instead of the shapefile. The .csv includes unmapped records. 
The data it pulls down for the Aug 11th 2021 release has 1309 more records than same version of dcp_facilities, which matches what I've seen before when debugging this issue.
> New template for dcp_facilities_with_unmapped

- library/templates/dcp_cb2010.yml
- library/templates/dcp_cb2010_wi.yml
- library/templates/dcp_cb2020.yml
- library/templates/dcp_cb2020_wi.yml
- library/templates/dcp_cdta2020.yml
- library/templates/dcp_congressionaldistricts.yml
- library/templates/dcp_nta2010.yml
- library/templates/dcp_nta2020.yml
- library/templates/dcp_ntaboundaries.yml
This PR addresses issue number #249 in data library but should also address a larger projection issue that was found in the QA/QC process for https://github.com/NYCPlanning/db-pluto/issues/315. In db-pluto, @AmandaDoyle found that there were records where census tracts were being populated but the census block column was not which didn't make any sense. @Oysters1874 and I took a look into what the issue might be and she found that the spatial join in db-pluto between census block and tract worked if you specified the projection of the census block files in the join which led us to think that there was an issue with the projection coming from data library. 
We discovered that there was a misspelling in the census block files (dcp_cb2020, dcp_cb2020_wi, etc...) with a value in the template …
> fix typo in various dcp_ data library templates

- library/templates/pluto_corrections.yml
After testing, the [PR](https://github.com/NYCPlanning/db-data-library/pull/257) to #256. I found that the `pluto_corrections` template did not download properly using the library archive commands, this PR addresses the minor fix and standardizes the `options` parameters `X_POSSIBLE_NAMES` and `Y_POSSIBLE_NAMES` to match the `dcla_culturalinstitutions` template
> 258 fix pluto corrections template

- .github/workflows/single-runner.yml
This PR addresses #267. One reviewer required ⭐ .
Generally, we have been updating `edm-recipe` datasets via the command line with `library archive` but a github action was set up to facilitate these uploads that wasn't widely used. When trying to upload the default `dcp_mappluto` dataset earlier, an `assertionerror` was thrown because of the way PLUTO datasets are versioned via data library (`22v2 or 22v3` as supposed to other datasets which are versioned by the date i.e. `20221121`. This PR adds a parameter to the workflow in which the user has to specify a version to upload to data library. 
To test, I ran the workflow off this branch which can be viewed here: https://github.com/NYCPlanning/db-data-library/actions/runs/3517220403
To confirm this action successfully ran, I checked the …
> Add Version Parameter to Upload Single Dataset Workflow 

- library/templates/dcp_boroboundaries.yml
- library/templates/dcp_boroboundaries_wi.yml
One reviewer required. Addresses issue #276  and two tasks in#272. Mistakenly named the feature branch 275 instead of 276.
> Update  URL path for `dcp_boroboundaries` and `dcp_boroboundaries_wi`

- library/templates/dcp_cb2020.yml
- library/templates/dcp_cb2020_wi.yml
One reviewer required. Addresses issue #280  and two tasks in #272.
> Update Url for `dcp_cb2020_wi` & `dcp_cb2020` 

- library/templates/dcp_cdta2020.yml
One reviewer required. Addresses issue #284 and one task in #272
> Update url path `dcp_cdta2020`

- library/templates/dcp_stateassemblydistricts.yml
- library/templates/dcp_stateassemblydistricts_wi.yml
#293 see spike issue #272 
two in one since they are both state assembly districts.
Should be no downstream impacts.
> update url path for `dcp_stateassemblydistricts` and `dcp_stateassemblydistricts_wi`

- library/templates/dcp_nta2010.yml
- library/templates/dcp_nta2020.yml
- library/templates/dcp_ntaboundaries.yml
#299 see #272 for spike issue
update urls for all nta templates.
after some investigation it was determined that the `dcp_ntaboundaries` is going to be the same as `dcp_nta2020`.
> update url `dcp_nta2010`, `dcp_nta2020` & `dcp_ntaboundaries`

- library/templates/dcp_ct2010.yml
- library/templates/dcp_ct2010_wi.yml
One reviewer required. Addresses issue #305  and two tasks in #272 .
> update url for  `dcp_ct2010_wi` and  `dcp ct2010`

- library/templates/dcp_zoningtaxlots.yml
Addresses issue #321 and one task in #272. One reviewer required ⭐ 
> update url `dcp_zoningtaxlots`

- library/templates/dcp_mappluto_wi.yml
one reviewer #328 
KPDB use `dcp_mappluto_wi` and currently the latest is 22v2 on DO. 
I know we were holding off updating mappluto related templates before. After considering the consequences of making updates, I believe we will need to be careful with updating `dcp_mappluto` or `dcp_mappluto_clipped` but for any datasets already using `dcp_mappluto_wi` already it should be no impact for us to update the url. But please let me know if I didn't cover all my bases when thinking this through. 
Once this is merged in and updated. I think we are ready to build KPDB.
> update dcp_mappluto_wi template

- library/templates/foodbankny_foodbanks.yml
Addresses issue #338. One reviewer required ⭐ 
Had some issues downloading and converting the kml/kmz files to a csv directly from the GoogleMap [here](https://www.google.com/maps/d/u/0/viewer?mid=1uVjjVxXfLFU4R6V7qjXXRoxCy-IwfMSP&ll=40.706960814039434%2C-73.97175925000002&z=10). The original directions stated that they should be downloaded and converted via a specific kml to csv convertor found on the internet but I found that making a copy of the map and then just exporting the layer as a csv worked best. I also implemented the version parameter which is standard on most of our templates. 
I ran locally and archive worked as expected.
Let me know if you have any questions or concerns
> Update `foodbankny_foodbanks` to pass a version and update directions

- library/templates/usdot_ports.yml
One reviewer required. Addresses issue #341.
After some more sleuthing, I found a dataset that matches the older version of the `usdot_ports` dataset we need for facilities database. To test, you can run this locally (withour pushing to s3) and view the file as a csv. This dataset contains records "_The location of a manmade water-land interface structure often used for access to boats or ships.
The Docks dataset was compiled on June 08, 2020 from the United States Army Corp of Engineers (USACE) and is part of the U.S. Department of Transportation (USDOT)/Bureau of Transportation Statistics (BTS) National Transportation Atlas Database (NTAD). The dataset contains physical information on commercial facilities at U.S. Coastal, Great Lakes and Inland Ports. The data consists of location …
> Update URL for `usdot_ports`

- library/script/bpl_libraries.py
one reviewer is fine 🌞 
#336 
An issue where the position field where we got the lat long for the record is breaking because blank `position` would not be able to handled by the extraction logics.
I will admit it is a pretty hacky way to handle the error but I don't believe it would break anything else. Tested locally on my machine and output seems in line with what we had in the past. The lat long for the empty position record would both be empty strings.
> bpl_libraries handle empty position field

- library/templates/doe_lcgms.yml
#340 one reviewer required
Changing the template back to using the manually download to because `aspx` protocol this dataset uses makes the programatic way to pull the dataset unsustainable. See `library/script/doe_lcgms.py` for the script to pull dataset and instructions from before.
the new template at `library/templates/doe_lcgms.yml` includes some new instructions about the downloadable workbook upload process and eccentricity about its naming and file format.
> doe lcgms manual upload

- library/templates/foodbankny_foodbanks.yml
One reviewer required. Addresses issue #344.
Add to existing description to properly rename the file with correct date format i.e YYYYDDMM
> Add updated description to `foodbankny_foodbanks` to properly format date 

- library/script/doe_lcgms.py
- library/templates/doe_lcgms.yml
Third time the charm hopefully for #340 
After @mbh329 facdb ingestion would [throw an encoding error](https://github.com/NYCPlanning/db-facilities/actions/runs/3760589448/jobs/6391467528) on the `doe_lcgms` which took me back to the drawing board and reactivate the script process to ingest the dataset. 
The new workflow requires a two-step process which is documented in the `library/templates/doe_lcgms.yml`. First, manually download the `.xls` file then convert it into a `utf-8` encoding csv. Then after it is moved to the `tmp` folder, the `library/script/doe_lcgms.py` script can be run to finish the upload. 
I opted to write another separate function for the new process of ingesting the csv because I don't feel entirely comfortable yet to delete all the works from before to work with …
> Use script to add encoding for `doe_lcgms`

- .github/workflows/quaterly-updates.yml
This issue addresses #330. One reviewer req ⭐ 
`dcp_pad` is a critical dataset for our db-gru-qaqc checks and hasn't been updated regularly. It is released on a quarterly cycle and therefore should be updated along with the other quarterly updates.
> Add `dcp_pad` to Bytes Quartely Update Workflow and reorder datasets alphabetically 

- library/templates/dcp_colp.yml
Addresses issue #361. 
Note:
* I changed this back in the beginning of December (PR #287) but when COLP was updated at the end of the Dec., the url changed to reflect the changes in the server that now hosts bytes of the big apple https://www.nyc.gov/site/planning/data-maps/open-data/dwn-colp.page. 
* To test you can use this command `library archive -n dcp_colp -v 202212` on this feature branch
> update dcp_colp url

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/workflows/test.yml
- Dockerfile
- poetry.lock
* pin poetry version to version seen in [latest tests on `main`](https://github.com/NYCPlanning/db-data-library/actions/runs/4107316691/jobs/7086643351#step:6:19)
* this PR is a follow up to https://github.com/NYCPlanning/db-data-library/pull/366 and replaces https://github.com/NYCPlanning/db-data-library/pull/347
* can't use original PR (https://github.com/NYCPlanning/db-data-library/pull/347) because it's a branch in SPTKL's remote repo so we can't push new commits to that branch
* [test failing in this PR](https://github.com/NYCPlanning/db-data-library/actions/runs/4126557517/jobs/7128641634#step:7:118) is known and expected pytest failure, same as on `main`
> pin poetry version

- library/templates/dcp_mappluto.yml
Addresses issue #372. Related to issue #316. 
Notes:
* `dcp_mappluto` and `dcp_mappluto_wi` are historically and currently the same thing. A change was never implemented to address the newer naming convention that is in place for other source datasets in which the `_wi` suffix relates to files that include water vs the absence of `_wi` which are clipped to the shoreline. As of now, we will continue to keep them the same until more research is done to understand the impact of this. 
* This datasets url change when the Bytes server changed urls - we need to update this in order to ingest 22v3 mappluto which is ingested via the new url
> Update `dcp_mappluto` url to new bytes server

- library/templates/cbbr_submissions.yml
Notes:
* Addresses issue #374 and connected to [issue 27 in db-ccbr](https://github.com/NYCPlanning/db-cbbr/issues/27).
* Create a yaml template to manually ingest cbbr_submissions data based of excel spreadsheet we received from strategic planning
* To test, I ingested the data locally and viewed the csv files so that the data persisted as expected. In the original xlsx, a `vlookup` function was used to get key value pairs in certain columns which created invalid data when saving the file into a csv. To bypass this, I saved the values in the columns as they appeared (negating any need for a lookup).
* Outputs are available in [DO](https://cloud.digitalocean.com/spaces/edm-recipes?i=266877&path=datasets%2Fcbbr_submissions%2F20230215%2F)
> Add template for `cbbr_submissions`

- library/script/dob_now_applications.py
- library/templates/dob_now_applications.yml
Addresses issue #376. 
Notes:
- After running a devdb build, there were errors in the log pointing to "odd" column name changes in which special characters were being inserted into the column schema. I checked the `dob_now_application.csv` encoding and found that the new .CSV DOB(downloaded via their FTP)  gave us is in utf-8 as supposed to older versions of the file which were encoded in Windows-1252. See dev-db build log [here](https://github.com/NYCPlanning/db-developments/actions/runs/4196116376/jobs/7276639078#step:9:69)
- Adding a note to the template to view the csv encoding type before upload 
- feature branch issue is misnamed, should be `376-dob-now...` MY BAD
> Change encoding of `dob_now_application.py` script to utf-8

- .github/workflows/update_image.yml
And one other. See this failure
https://github.com/NYCPlanning/db-data-library/actions/runs/4734381721/jobs/8403220541
Workflows triggered by 'push' have no access to 'default' value for the workflow dispatch input, so need to specify another way
Fixed in below action, on push in this branch
https://github.com/NYCPlanning/db-data-library/actions/runs/4734427865
Verification that other option can be specified when using workflow dispatch (had swapped whether latest/staging was default here)
https://github.com/NYCPlanning/db-data-library/actions/runs/4734465371
> Default input missing on push triggering workflow

- .github/workflows/single-runner.yml
When I updated the single runner yaml file [here](https://github.com/NYCPlanning/db-data-library/pull/385/files#diff-b214fd847afeabec30ea7b7a218332895fd7fcbd23322b1fa8e3936b7dfddb4f), messed up the logic around version being specified
See failed run here:
https://github.com/NYCPlanning/db-data-library/actions/runs/4787598456/jobs/8513040987
`--version` was not being added, but instead the version was just added as an extraneous argument
Rerunning now
https://github.com/NYCPlanning/db-data-library/actions/runs/4787740610
> Single runner version bug

- .github/workflows/update_image.yml
Before, we were using [this action](https://github.com/docker-practice/actions-setup-docker) to setup docker and run via commands. This was having some sort of internal failure while installing things via `apt-get`.
With these changes, we're no longer setting up docker, but logging, buildling and pushing via [docker's official published actions](https://github.com/docker). Specifically, [login-action](https://github.com/docker/login-action) and [build-push-action](https://github.com/docker/build-push-action)
See changes in original push to main [here](https://github.com/NYCPlanning/db-data-library/commit/347654eeeaeaf8292e4071c40d864baa8d79ed3c)
See failing workflow runs prior to changes [here](https://github.com/NYCPlanning/db-data-library/actions/runs/4799942161/jobs/8540236685).
> Fvk fix docker image publication

- library/ingest.py
- ensure the `version` string matches the sql table name (which is automatically lowercase) after it's been written to the `edm-data.recipes` DB
> fix archiving to postgres

- library/config.py
The `compute` property in `Config` calls `Scriptor.runner()` if the source for a data set is a python script. In `Ingestor.translator`, there are potentially 3 total calls to this property, one via `compute_parsed` [here](https://github.com/NYCPlanning/db-data-library/blob/main/library/ingest.py#L55) and then two others via `Config.compute_json` and `compute_yml` [here](https://github.com/NYCPlanning/db-data-library/blob/main/library/ingest.py#L85) (each of these three properties reference the `compute` property). 
In cases where `Scriptor.runner()` is making web calls (such as [doitt_building_footprints](https://github.com/NYCPlanning/db-data-library/actions/runs/4724962876/jobs/8382817005)), this is causing 3 calls to download the same file, each time creating a new temporary download …
> Cache Config.compute property

- library/ingest.py
- tests/__init__.py
- tests/data/bpl_libraries_sql.yml
- tests/data/url.yml
- tests/test_config.py
- tests/test_ingest.py
Closes #398 and adds test for a sql group by statement in vector translate
Copying text from issue:
> So a fairly innocuous looking change was made here
>
> https://github.com/NYCPlanning/db-data-library/commit/3803454a7edf724c7d48440297885e615193c7d1#diff-5a31bf7a3838bfb58f602bce217962045a1c1dde0f950dc28c397c7a6909ef5eR128
>
> As far as I can tell, we only have one dataset that actually uses this functionality
>
> https://github.com/NYCPlanning/db-pluto/actions/workflows/input_numbldgs.yml
>
> And has been failing since this change. Testing locally, reverting to sqlite work. Looking at [gdal docs](https://gdal.org/user/sql_sqlite_dialect.html) the `SQLDialect` option in `VectorTranslate` might only support the native "OGR SQL" and sqlite. So it might just be falling back to ogr which …
> Fix sql statement in GDAL VectorTranslate

- library/script/bpl_libraries.py
- library/script/dcp_censusdata.py
- library/script/dcp_censusdata_blocks.py
- library/script/dcp_colp.py
- library/script/dob_now_applications.py
- library/script/dob_now_permits.py
- library/script/doe_lcgms.py
- library/script/doe_pepmeetingurls.py
- library/script/moeo_socialservicesitelocations.py
- library/script/nycdoc_corrections.py
- library/script/nysed_nonpublicenrollment.py
- library/script/usdot_airports.py
- library/templates/bpl_libraries.yml
- library/templates/dcp_censusdata.yml
- library/templates/dcp_censusdata_blocks.yml
- tests/data/bpl_libraries_sql.yml
Two things.
- primary purpose - add yml templates and python scripts for dcp-provided census data for population and housing. There are two source files - one by blocks/borough/city, and one by ntas/community districts/council districts/borough/city. 
- some maintenance - a while back I edited a bunch of the scripts and made it so that path was specified in yml, not just hard-coded in a script (in the case of `script`-sourced dataset that are still pulling from just one endpoint). I missed bpl_libraries back then so added it now (and in the one test yml file that uses it)
> Add census data

- library/utils.py
Addresses bug in #402 to at least not fail when attempt to grab git username fails
> fix `try...except` clause only wrapping final call of subprocess output

- README.md
- library/script/hpd_historical_units_by_building.py
- library/templates/hpd_historical_units_by_building.yml
related to https://github.com/NYCPlanning/data-engineering/issues/30
- be able to archive new source data: HPD Historical Units by Project (`hpd_historical_units_by_building`)
- add template file and python script
- change readme to have a more common example of `library archive` arguments
- emulates approach for similar source data `hpd_hny_units_by_building`
- screenshot of archived data in `edm-recipes` S3 bucket: <img width="833" alt="image" src="https://github.com/NYCPlanning/db-data-library/assets/7444289/f5704e85-4817-40bd-8905-23ef68cd7c9d">
- [successful use](https://github.com/NYCPlanning/data-engineering/actions/runs/5446509203/jobs/9907693169#step:4:145) of the archived data in a downstream process
> add hpd historical data

- library/cli.py
- library/ingest.py
- library/s3.py
- library/sources.py
- library/templates/dcp_pop_acs.yml
- library/templates/dcp_pop_decennial_dhc.yml
- library/validator.py
Added a raw file dump option (skip gdal), which needed:
- add "as_is" translator function
- modify ingest so that when "as_is" is specified as output format, gdal logic (and other logic around dstDS, srcDS, layerName, etc) is skipped and file is simply dumped to output location
Open to other names for this output format option!
Also added two templates, xlsx files which feed into pff and are therefor needed in their xlsx format. Could theoretically replace with script that has some logic of PFF but this seems like cleaner route for now, I don't have philosophical objection to having recipes that skip gdal. 
Other small changes
- Needed to extend the read_timeout for s3 client for these large xlsx files
- cleaned up some imports
> add 'as_is' output format option

- library/__init__.py
- library/ingest.py
- library/utils.py
First part should be self-explanatory.
For second part, I've been doing some testing locally with cpdb shape files. Currently, if a zipped shapefile is invalid in some way, this is discovered by loading the dataset without using exceptions, then [raising an error](https://github.com/NYCPlanning/db-data-library/blob/main/library/sources.py#L69) with `assert` if the dataset is `None`. It seems a bit more helpful to actually let gdal throw the error while loading the dataset instead (though in this case it does just say only slightly more verbosely that the zip file is not in a supported format). A little nervous about side-effects of this - do we have existing known "errors" that should be ignored? Should we always be throwing errors? I would think yes - a little odd that right now we only …
> Allow subpath for local zip archives, use gdal exceptions sooner in process
